### ISSUE TITLE
nagios problems after install

### ISSUE THREAD

**Issue by gustavoberman** [sdsc/nagios-roll#1]
Hi there!
Thanks for the roll!

I had a couple of problems after install:

1- nagios didn't start because it was missing a service. The initial service described in the manual wasn't created. I created it and then nagios started ok.

2- cgi didn't show any info. I had to append this 2 lines to _/opt/nagios/etc/nagios.cfg_:

```
state_retention_file=/opt/nagios/var/retention.dat
status_file=/opt/nagios/var/status.dat

```

**Comment by jjhayes** [comment]
Hi Gustav,

Thanks for the report; I'm glad that you're finding the roll useful.

I'll look into the missing service you mentioned, and I'll check into adding those additional config lines you included in your message.

Jim

**Comment by jjhayes** [comment]
Hi Gustav,

I just incorporated your changes into the roll source.  Thanks again for sending along the fixes.

Jim
